### PR TITLE
Configure CodeQL Security Scanning

### PR DESCRIPTION
**Pull request by alistair-mx51**
This PR creates 2 configuration files so that CodeQL security scans will run on this repository on a weekly schedule. The PR has been generated programmatically so that it can be more easily applied to many repositories en masse. If there are any issues with it, please let @alistair-mx51 know via Slack or by replying to this PR.

### CODE REVIEW

**Review by awilmore — DISMISSED** [review]

**Comment by awilmore** [comment]
@alistair-mx51 @aquam8 I'm not sure what or where that `lint-chart` check is, nor why the other github actions didn't fire. We can't merge this one without overriding permissions and removing `lint-chart` from required checks/statuses.

**Comment by aquam8** [comment]
let me try to update the lint step..

**Comment by alistair-mx51** [comment]
> @alistair-mx51 @aquam8 I'm not sure what or where that `lint-chart` check is, nor why the other github actions didn't fire. We can't merge this one without overriding permissions and removing `lint-chart` from required checks/statuses.

I think that status check is stuck in pending state for the reason described [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths). In the branch protection settings for this repo, lint-chart is a status check that requires a pass result. Yet in the corresponding [GH Action workflow file](https://github.com/mx51/helm-chart-packages/blob/master/.github/workflows/ci.yaml), it's configured to only run when the PR involves changes to files in the `"stable/**"` path. 

So I think you'll either need to edit the branch protection settings (easy solution) or update the workflow file.

**Review by awilmore — APPROVED** [review]
👍

**Pull request merged**
